load data 
infile '/dbbackup/eicu/allergy.txt' "str '\n'"
append
into table allergy
fields terminated by '$!#'
--OPTIONALLY ENCLOSED BY '"' AND '"'
trailing nullcols
           ( 
ALLERGYID,
PATIENTUNITSTAYID,
ALLERGYYEAR,
ALLERGYTIME24,
ALLERGYTIME,
ALLERGYOFFSET,
ALLERGYENTEREDYEAR,
ALLERGYENTEREDTIME24,
ALLERGYENTEREDTIME,
ALLERGYENTEREDOFFSET,
ALLERGYNOTETYPE,
SPECIALTYTYPE,
USERTYPE,
RXINCLUDED,
WRITTENINEICU,
DRUGNAME,
ALLERGYTYPE,
ALLERYNAME,
DRUGHICLSEQNO
)
