SELECT 'CREATE TABLE ' ||table_name || ' AS SELECT *  FROM ' ||OWNER ||'.'|| table_name || ' where rownum<10;'
  FROM all_tables
 WHERE OWNER = 'EICU_ADM' and table_name != 'admissiondrug';
 
CREATE TABLE INFUSIONDRUG AS SELECT *  FROM EICU_ADM.INFUSIONDRUG where rownum<10;
CREATE TABLE DIAGNOSIS AS SELECT *  FROM EICU_ADM.DIAGNOSIS where rownum<10;
CREATE TABLE CAREPLANGENERAL AS SELECT *  FROM EICU_ADM.CAREPLANGENERAL where rownum<10;
CREATE TABLE INTAKEOUTPUT AS SELECT *  FROM EICU_ADM.INTAKEOUTPUT where rownum<10;
CREATE TABLE TREATMENT AS SELECT *  FROM EICU_ADM.TREATMENT where rownum<10;
CREATE TABLE MEDICATION AS SELECT *  FROM EICU_ADM.MEDICATION where rownum<10;
CREATE TABLE VITALAPERIODIC AS SELECT *  FROM EICU_ADM.VITALAPERIODIC where rownum<10;
CREATE TABLE LAB AS SELECT *  FROM EICU_ADM.LAB where rownum<10;
CREATE TABLE NURSECHARTING AS SELECT *  FROM EICU_ADM.NURSECHARTING where rownum<10;
CREATE TABLE VITALPERIODIC AS SELECT *  FROM EICU_ADM.VITALPERIODIC where rownum<10;
CREATE TABLE CAREPLANEOL AS SELECT *  FROM EICU_ADM.CAREPLANEOL where rownum<10;
CREATE TABLE APACHEAPSVAR AS SELECT *  FROM EICU_ADM.APACHEAPSVAR where rownum<10;
CREATE TABLE APACHEPREDVAR AS SELECT *  FROM EICU_ADM.APACHEPREDVAR where rownum<10;
CREATE TABLE MICROLAB AS SELECT *  FROM EICU_ADM.MICROLAB where rownum<10;
CREATE TABLE APACHEPATIENTRESULTS AS SELECT *  FROM EICU_ADM.APACHEPATIENTRESULTS where rownum<10;
CREATE TABLE CAREPLANINFECTIOUSDISEASE AS SELECT *  FROM EICU_ADM.CAREPLANINFECTIOUSDISEASE where rownum<10;
CREATE TABLE ADMISSIONDX AS SELECT *  FROM EICU_ADM.ADMISSIONDX where rownum<1;
CREATE TABLE PATIENT AS SELECT *  FROM EICU_ADM.PATIENT where rownum<10;
CREATE TABLE RESPIRATORYCARE AS SELECT *  FROM EICU_ADM.RESPIRATORYCARE where rownum<10;
CREATE TABLE ADMISSIONDRUG AS SELECT *  FROM EICU_ADM.ADMISSIONDRUG where rownum<10;
CREATE TABLE SPERRORLOG AS SELECT *  FROM EICU_ADM.SPERRORLOG where rownum<10;
CREATE TABLE RESPIRATORYCHARTING AS SELECT *  FROM EICU_ADM.RESPIRATORYCHARTING where rownum<10;
CREATE TABLE RSREPORTBUCKET AS SELECT *  FROM EICU_ADM.RSREPORTBUCKET where rownum<10;
CREATE TABLE ADMISSIONDRUG_NEW AS SELECT *  FROM EICU_ADM.ADMISSIONDRUG_NEW where rownum<10;

drop table admissiondrug_new;

alter table admissionDx drop column PARTITIONKEY;

drop table admissionDx;

delete from admissionDx where rownum>0;
delete from APACHEAPSVAR where rownum<10;
delete from APACHEPATIENTRESULTS where rownum<10;
delete from APACHEPREDVAR where rownum<10;
delete from CAREPLANEOL where rownum<10;
delete from CAREPLANGENERAL where rownum<10;
delete from CAREPLANINFECTIOUSDISEASE where rownum<10;
delete from DIAGNOSIS where rownum<10;
delete from INFUSIONDRUG where rownum<10;
delete from INTAKEOUTPUT where rownum<10;
delete from LAB where rownum<10;
delete from MEDICATION where rownum<10;
delete from MICROLAB where rownum<10;
delete from NURSECHARTING where rownum<10;
delete from PATIENT where rownum<10;
delete from RESPIRATORYCARE where rownum<10;
delete from RESPIRATORYCHARTING where rownum<10;
delete from RSREPORTBUCKET where rownum<10;
delete from SPERRORLOG where rownum<10;
delete from TREATMENT where rownum<10;
delete from VITALAPERIODIC where rownum<10;
delete from VITALPERIODIC where rownum<10;





