--------------------------------------------------------
--  File created - Thursday-March-19-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADMISSIONDRUG
--------------------------------------------------------

  CREATE TABLE "EICU_V1"."ADMISSIONDRUG" 
   (	"ADMISSIONDRUGID" VARCHAR2(16 BYTE), 
	"PATIENTUNITSTAYID" VARCHAR2(16 BYTE), 
	"DRUGYEAR" VARCHAR2(8 BYTE), 
	"DRUGTIME24" VARCHAR2(16 BYTE), 
	"DRUGTIME" VARCHAR2(16 BYTE), 
	"DRUGOFFSET" VARCHAR2(16 BYTE), 
	"DRUGENTEREDYEAR" VARCHAR2(8 BYTE), 
	"DRUGENTEREDTIME24" VARCHAR2(16 BYTE), 
	"DRUGENTEREDTIME" VARCHAR2(16 BYTE), 
	"DRUGENTEREDOFFSET" VARCHAR2(16 BYTE), 
	"DRUGNOTETYPE" VARCHAR2(32 BYTE), 
	"SPECIALTYTYPE" VARCHAR2(32 BYTE), 
	"USERTYPE" VARCHAR2(32 BYTE), 
	"RXINCLUDED" VARCHAR2(16 BYTE), 
	"WRITTENINEICU" VARCHAR2(16 BYTE), 
	"DRUGNAME" VARCHAR2(255 BYTE), 
	"DRUGDOSAGE" VARCHAR2(32 BYTE), 
	"DRUGUNIT" VARCHAR2(32 BYTE), 
	"DRUGADMITFREQUENCY" VARCHAR2(32 BYTE), 
	"DRUGHICLSEQNO" VARCHAR2(32 BYTE), 
	"PARTITIONKEY" VARCHAR2(16 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EICU_V1" ;
--------------------------------------------------------
--  DDL for Table ADMISSIONDX
--------------------------------------------------------

  CREATE TABLE "EICU_V1"."ADMISSIONDX" 
   (	"ADMISSIONDXID" VARCHAR2(16 BYTE), 
	"PATIENTUNITSTAYID" VARCHAR2(16 BYTE), 
	"ADMITDXENTEREDYEAR" VARCHAR2(8 BYTE), 
	"ADMITDXENTEREDTIME24" VARCHAR2(16 BYTE), 
	"ADMITDXENTEREDTIME" VARCHAR2(16 BYTE), 
	"ADMITDXENTEREDOFFSET" VARCHAR2(16 BYTE), 
	"ADMITDXPATH" VARCHAR2(256 BYTE), 
	"ADMITDXNAME" VARCHAR2(256 BYTE), 
	"ADMITDXTEXT" VARCHAR2(256 BYTE), 
	"PARTITIONKEY" VARCHAR2(8 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EICU_V1" ;
--------------------------------------------------------
--  DDL for Table ALLERGY
--------------------------------------------------------

  CREATE TABLE "EICU_V1"."ALLERGY" 
   (	"ALLERGYID" NUMBER(32,0), 
	"PATIENTUNITSTAYID" NUMBER(32,0), 
	"ALLERGYYEAR" NUMBER(4,0), 
	"ALLERGYTIME24" VARCHAR2(8 BYTE), 
	"ALLERGYTIME" VARCHAR2(20 BYTE), 
	"ALLERGYOFFSET" NUMBER(32,0), 
	"ALLERGYENTEREDYEAR" NUMBER(4,0), 
	"ALLERGYENTEREDTIME24" VARCHAR2(8 BYTE), 
	"ALLERGYENTEREDTIME" VARCHAR2(20 BYTE), 
	"ALLERGYENTEREDOFFSET" NUMBER(32,0), 
	"ALLERGYNOTETYPE" VARCHAR2(255 BYTE), 
	"SPECIALTYTYPE" VARCHAR2(255 BYTE), 
	"USERTYPE" VARCHAR2(255 BYTE), 
	"RXINCLUDED" VARCHAR2(5 BYTE), 
	"WRITTENINEICU" VARCHAR2(5 BYTE), 
	"DRUGNAME" VARCHAR2(255 BYTE), 
	"ALLERGYTYPE" VARCHAR2(255 BYTE), 
	"ALLERYNAME" VARCHAR2(255 BYTE), 
	"DRUGHICLSEQNO" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EICU_V1" ;
--------------------------------------------------------
--  DDL for Table APACHEAPSVAR
--------------------------------------------------------

  CREATE TABLE "EICU_V1"."APACHEAPSVAR" 
   (	"APACHEAPSVARID" NUMBER(*,0), 
	"PATIENTUNITSTAYID" NUMBER(*,0), 
	"INTUBATED" VARCHAR2(64 BYTE), 
	"VENT" VARCHAR2(64 BYTE), 
	"DIALYSIS" VARCHAR2(64 BYTE), 
	"EYES" VARCHAR2(64 BYTE), 
	"MOTOR" VARCHAR2(64 BYTE), 
	"VERBAL" VARCHAR2(64 BYTE), 
	"MEDS" VARCHAR2(64 BYTE), 
	"URINE" VARCHAR2(64 BYTE), 
	"WBC" VARCHAR2(64 BYTE), 
	"TEMPERATURE" VARCHAR2(64 BYTE), 
	"RESPIRATORYRATE" VARCHAR2(64 BYTE), 
	"SODIUM" VARCHAR2(64 BYTE), 
	"HEARTRATE" VARCHAR2(64 BYTE), 
	"MEANBP" VARCHAR2(64 BYTE), 
	"PH" VARCHAR2(64 BYTE), 
	"HEMATOCRIT" VARCHAR2(64 BYTE), 
	"CREATININE" VARCHAR2(64 BYTE), 
	"ALBUMIN" VARCHAR2(64 BYTE), 
	"PAO2" VARCHAR2(64 BYTE), 
	"PCO2" VARCHAR2(64 BYTE), 
	"BUN" VARCHAR2(64 BYTE), 
	"GLUCOSE" VARCHAR2(64 BYTE), 
	"BILIRUBIN" VARCHAR2(64 BYTE), 
	"FIO2" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EICU_V1" ;
--------------------------------------------------------
--  DDL for Table APACHEPATIENTRESULTS
--------------------------------------------------------

  CREATE TABLE "EICU_V1"."APACHEPATIENTRESULTS" 
   (	"APACHEPATIENTSRESULTSID" NUMBER(*,0), 
	"PATIENTUNITSTAYID" NUMBER(*,0), 
	"PHYSICIANSPECIALITY" VARCHAR2(64 BYTE), 
	"PHYSICIANINTERVENTIONCATEGORY" VARCHAR2(64 BYTE), 
	"ACUTEPHYSIOLOGYSCORE" VARCHAR2(64 BYTE), 
	"APACHESCORE" VARCHAR2(64 BYTE), 
	"APACHEVERSION" VARCHAR2(64 BYTE), 
	"PREDICTEDICUMORTALITY" VARCHAR2(64 BYTE), 
	"ACTUALICUMORTALITY" VARCHAR2(64 BYTE), 
	"PREDICTEDICULOS" VARCHAR2(64 BYTE), 
	"ACTUALICULOS" VARCHAR2(64 BYTE), 
	"PREDICTEDHOSPITALMORTALITY" VARCHAR2(64 BYTE), 
	"ACTUALHOSPITALMORTALITY" VARCHAR2(64 BYTE), 
	"PREDICTEDHOSPITALLOS" VARCHAR2(64 BYTE), 
	"ACTUALHOSPITALLOS" VARCHAR2(64 BYTE), 
	"PREOPMI" VARCHAR2(64 BYTE), 
	"PREOPCARDIACCATH" VARCHAR2(64 BYTE), 
	"PTCAWITHIN24H" VARCHAR2(64 BYTE), 
	"UNABRIDGEDUNITLOS" VARCHAR2(64 BYTE), 
	"UNABRIDGEDHOSPLOS" VARCHAR2(64 BYTE), 
	"ACTUALVENTDAYS" VARCHAR2(64 BYTE), 
	"PREDVENTDAYS" VARCHAR2(64 BYTE), 
	"UNABRIDGEDACTUALVENTDAYS" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EICU_V1" ;
--------------------------------------------------------
--  DDL for Table APACHEPREDVAR
--------------------------------------------------------

  CREATE TABLE "EICU_V1"."APACHEPREDVAR" 
   (	"APACHEPREDVARID" NUMBER(*,0), 
	"PATIENTUNITSTAYID" NUMBER(*,0), 
	"SICUDAY" VARCHAR2(64 BYTE), 
	"SAPS3DAY1" VARCHAR2(64 BYTE), 
	"SAPS3TODAY" VARCHAR2(64 BYTE), 
	"SAPS3YESTERDAY" VARCHAR2(64 BYTE), 
	"GENDER" VARCHAR2(64 BYTE), 
	"TEACHTYPE" VARCHAR2(64 BYTE), 
	"REGION" VARCHAR2(64 BYTE), 
	"BEDCOUNT" VARCHAR2(64 BYTE), 
	"ADMITSOURCE" VARCHAR2(64 BYTE), 
	"GRAFTCOUNT" VARCHAR2(64 BYTE), 
	"MEDS" VARCHAR2(64 BYTE), 
	"VERBAL" VARCHAR2(64 BYTE), 
	"MOTOR" VARCHAR2(64 BYTE), 
	"EYES" VARCHAR2(64 BYTE), 
	"AGE" VARCHAR2(64 BYTE), 
	"ADMITDIAGNOSIS" VARCHAR2(64 BYTE), 
	"THROMBOLYTICS" VARCHAR2(64 BYTE), 
	"DIEDINHOSPITAL" VARCHAR2(64 BYTE), 
	"AIDS" VARCHAR2(64 BYTE), 
	"HEPATICFAILURE" VARCHAR2(64 BYTE), 
	"LYMPHOMA" VARCHAR2(64 BYTE), 
	"METASTATICCANCER" VARCHAR2(64 BYTE), 
	"LEUKEMIA" VARCHAR2(64 BYTE), 
	"IMMUNOSUPPRESSION" VARCHAR2(64 BYTE), 
	"CIRRHOSIS" VARCHAR2(64 BYTE), 
	"ELECTIVESURGERY" VARCHAR2(64 BYTE), 
	"ACTIVETX" VARCHAR2(64 BYTE), 
	"READMIT" VARCHAR2(64 BYTE), 
	"IMA" VARCHAR2(64 BYTE), 
	"MIDUR" VARCHAR2(64 BYTE), 
	"VENTDAY1" VARCHAR2(64 BYTE), 
	"OOBVENTDAY1" VARCHAR2(64 BYTE), 
	"OOBINTUBDAY1" VARCHAR2(64 BYTE), 
	"DIABETES" VARCHAR2(64 BYTE), 
	"MANAGEMENTSYSTEM" VARCHAR2(64 BYTE), 
	"VAR03HSPXLOS" VARCHAR2(64 BYTE), 
	"PAO2" VARCHAR2(64 BYTE), 
	"FIO2" VARCHAR2(64 BYTE), 
	"EJECTFX" VARCHAR2(64 BYTE), 
	"CREATININE" VARCHAR2(64 BYTE), 
	"DISCHARGELOCATION" VARCHAR2(64 BYTE), 
	"VISITNUMBER" VARCHAR2(64 BYTE), 
	"AMILOCATION" VARCHAR2(64 BYTE), 
	"DAY1MEDS" VARCHAR2(64 BYTE), 
	"DAY1VERBAL" VARCHAR2(64 BYTE), 
	"DAY1MOTOR" VARCHAR2(64 BYTE), 
	"DAY1EYES" VARCHAR2(64 BYTE), 
	"DAY1PAO2" VARCHAR2(64 BYTE), 
	"DAY1FIO2" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EICU_V1" ;
--------------------------------------------------------
--  DDL for Table BILLING
--------------------------------------------------------

  CREATE TABLE "EICU_V1"."BILLING" 
   (	"BILLINGID" NUMBER(*,0), 
	"PATIENTUNITSTAYID" NUMBER(*,0), 
	"BILLINGYEAR" VARCHAR2(64 BYTE), 
	"BILLINGTIME24" VARCHAR2(64 BYTE), 
	"BILLINGTIME" VARCHAR2(64 BYTE), 
	"BILLINGOFFSET" VARCHAR2(64 BYTE), 
	"BILLINGENTEREDYEAR" VARCHAR2(64 BYTE), 
	"BILLINGENTEREDTIME24" VARCHAR2(64 BYTE), 
	"BILLINGENTEREDTIME" VARCHAR2(64 BYTE), 
	"BILLINGENTEREDOFFSET" VARCHAR2(64 BYTE), 
	"BILLINGTYPE" VARCHAR2(64 BYTE), 
	"BILLINGPATH" VARCHAR2(500 BYTE), 
	"BILLINGNAME" VARCHAR2(400 BYTE), 
	"BILLINGVALUE" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EICU_V1" ;
--------------------------------------------------------
--  DDL for Table CAREPLANCAREPROVIDER
--------------------------------------------------------

  CREATE TABLE "EICU_V1"."CAREPLANCAREPROVIDER" 
   (	"CPLCAREPROVDERID" NUMBER(*,0), 
	"PATIENTUNITSTAYID" NUMBER(*,0), 
	"CAREPROVIDERSAVEYEAR" VARCHAR2(64 BYTE), 
	"CAREPROVIDERSAVETIME24" VARCHAR2(64 BYTE), 
	"CAREPROVIDERSAVETIME" VARCHAR2(64 BYTE), 
	"CAREPROVIDERSAVEOFFSET" VARCHAR2(64 BYTE), 
	"PROVIDERTYPE" VARCHAR2(256 BYTE), 
	"SPECIALTY" VARCHAR2(256 BYTE), 
	"INTERVENTIONCATEGORY" VARCHAR2(256 BYTE), 
	"MANAGINGPHYSICIAN" VARCHAR2(64 BYTE), 
	"ACTIVEUPONDISCHARGE" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EICU_V1" ;
--------------------------------------------------------
--  DDL for Table CAREPLANEOL
--------------------------------------------------------

  CREATE TABLE "EICU_V1"."CAREPLANEOL" 
   (	"CPLEOLID" NUMBER(*,0), 
	"PATIENTUNITSTAYID" NUMBER(*,0), 
	"CPLEOLSAVEYEAR" VARCHAR2(64 BYTE), 
	"CPLEOLSAVETIME24" VARCHAR2(64 BYTE), 
	"CPLEOLSAVETIME" VARCHAR2(64 BYTE), 
	"CPLEOLSAVEOFFSET" VARCHAR2(64 BYTE), 
	"CPLEOLDISCUSSIONYEAR" VARCHAR2(64 BYTE), 
	"CPLEOLDISCUSSIONTIME24" VARCHAR2(64 BYTE), 
	"CPLEOLDISCUSSIONTIME" VARCHAR2(64 BYTE), 
	"CPLEOLDISCUSSIONOFFSET" VARCHAR2(64 BYTE), 
	"ACTIVEUPONDISCHARGE" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EICU_V1" ;
--------------------------------------------------------
--  DDL for Table CAREPLANGENERAL
--------------------------------------------------------

  CREATE TABLE "EICU_V1"."CAREPLANGENERAL" 
   (	"CPLGENERALID" NUMBER(*,0), 
	"PATIENTUNITSTAYID" NUMBER(*,0), 
	"CPLITEMYEAR" VARCHAR2(64 BYTE), 
	"CPLITEMTIME24" VARCHAR2(64 BYTE), 
	"CPLITEMTIME" VARCHAR2(64 BYTE), 
	"CPLITEMOFFSET" VARCHAR2(64 BYTE), 
	"CPLGROUP" VARCHAR2(256 BYTE), 
	"CPLITEMVALUE" VARCHAR2(1024 BYTE), 
	"ACTIVEUPONDISCHARGE" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EICU_V1" ;
--------------------------------------------------------
--  DDL for Table CAREPLANGOAL
--------------------------------------------------------

  CREATE TABLE "EICU_V1"."CAREPLANGOAL" 
   (	"CPLGOALID" NUMBER(*,0), 
	"PATIENTUNITSTAYID" NUMBER(*,0), 
	"CPLGOALYEAR" VARCHAR2(64 BYTE), 
	"CPLGOALTIME24" VARCHAR2(64 BYTE), 
	"CPLGOALTIME" VARCHAR2(64 BYTE), 
	"CPLGOALOFFSET" VARCHAR2(64 BYTE), 
	"CPLGOALCATEGORY" VARCHAR2(256 BYTE), 
	"CPLGOALVALUE" VARCHAR2(1000 BYTE), 
	"CPLGOALSTATUS" VARCHAR2(256 BYTE), 
	"ACTIVEUPONDISCHARGE" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EICU_V1" ;
--------------------------------------------------------
--  DDL for Table CAREPLANINFECTIOUSDISEASE
--------------------------------------------------------

  CREATE TABLE "EICU_V1"."CAREPLANINFECTIOUSDISEASE" 
   (	"CPLINFECTID" VARCHAR2(16 BYTE), 
	"PATIENTUNITSTAYID" VARCHAR2(16 BYTE), 
	"CPLINFECTDISEASEYEAR" VARCHAR2(8 BYTE), 
	"CPLINFECTDISEASETIME24" VARCHAR2(16 BYTE), 
	"CPLINFECTDISEASETIME" VARCHAR2(16 BYTE), 
	"CPLINFECTDISEASEOFFSET" VARCHAR2(16 BYTE), 
	"INFECTDISEASESITE" VARCHAR2(64 BYTE), 
	"INFECTDISEASEASSESSMENT" VARCHAR2(64 BYTE), 
	"RESPONSETOTHERAPY" VARCHAR2(32 BYTE), 
	"TREATMENT" VARCHAR2(32 BYTE), 
	"ACTIVEUPONDISCHARGE" VARCHAR2(32 BYTE), 
	"PARTITIONKEY" VARCHAR2(16 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EICU_V1" ;
--------------------------------------------------------
--  DDL for Table CUSTOMLAB
--------------------------------------------------------

  CREATE TABLE "EICU_V1"."CUSTOMLAB" 
   (	"CUSTOMLABID" NUMBER(*,0), 
	"PATIENTUNITSTAYID" NUMBER(*,0), 
	"LABOTHERYEAR" VARCHAR2(64 BYTE), 
	"LABOTHERTIME24" VARCHAR2(64 BYTE), 
	"LABOTHERTIME" VARCHAR2(64 BYTE), 
	"LABOTHEROFFSET" VARCHAR2(64 BYTE), 
	"LABOTHERTYPEID" VARCHAR2(64 BYTE), 
	"LABOTHERNAME" VARCHAR2(64 BYTE), 
	"LABOTHERRESULT" VARCHAR2(64 BYTE), 
	"LABOTHERVALUETEXT" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EICU_V1" ;
--------------------------------------------------------
--  DDL for Table DIAGNOSIS
--------------------------------------------------------

  CREATE TABLE "EICU_V1"."DIAGNOSIS" 
   (	"DIAGNOSISID" NUMBER(*,0), 
	"PATIENTUNITSTAYID" NUMBER(*,0), 
	"DIAGNOSISYEAR" VARCHAR2(64 BYTE), 
	"DIAGNOSISTIME24" VARCHAR2(64 BYTE), 
	"DIAGNOSISTIME" VARCHAR2(64 BYTE), 
	"DIAGNOSISOFFSET" VARCHAR2(64 BYTE), 
	"DIAGNOSISSTRING" VARCHAR2(200 BYTE), 
	"ACTIVEUPONDISCHARGE" VARCHAR2(64 BYTE), 
	"ICD9CODE" VARCHAR2(100 BYTE), 
	"DIAGNOSISPRIORITY" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EICU_V1" ;
--------------------------------------------------------
--  DDL for Table INFUSIONDRUG
--------------------------------------------------------

  CREATE TABLE "EICU_V1"."INFUSIONDRUG" 
   (	"INFUSIONDRUGID" NUMBER(*,0), 
	"PATIENTUNITSTAYID" NUMBER(*,0), 
	"INFUSIONYEAR" VARCHAR2(64 BYTE), 
	"INFUSIONTIME24" VARCHAR2(64 BYTE), 
	"INFUSIONTIME" VARCHAR2(64 BYTE), 
	"INFUSIONOFFSET" VARCHAR2(64 BYTE), 
	"DRUGNAME" VARCHAR2(256 BYTE), 
	"DRUGRATE" VARCHAR2(256 BYTE), 
	"INFUSIONRATE" VARCHAR2(256 BYTE), 
	"DRUGAMOUNT" VARCHAR2(256 BYTE), 
	"VOLUMEOFFLUID" VARCHAR2(256 BYTE), 
	"PATIENTWEIGHT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EICU_V1" ;
--------------------------------------------------------
--  DDL for Table INTAKEOUTPUT
--------------------------------------------------------

  CREATE TABLE "EICU_V1"."INTAKEOUTPUT" 
   (	"INTAKEOUTPUTID" NUMBER(*,0), 
	"PATIENTUNITSTAYID" NUMBER(*,0), 
	"INTAKEOUTPUTYEAR" VARCHAR2(64 BYTE), 
	"INTAKEOUTPUTTIME24" VARCHAR2(64 BYTE), 
	"INTAKEOUTPUTTIME" VARCHAR2(64 BYTE), 
	"INTAKEOUTPUTOFFSET" VARCHAR2(64 BYTE), 
	"INTAKETOTAL" VARCHAR2(64 BYTE), 
	"OUTPUTTOTAL" VARCHAR2(64 BYTE), 
	"DIALYSISTOTAL" VARCHAR2(64 BYTE), 
	"NETTOTAL" VARCHAR2(64 BYTE), 
	"INTAKEOUTPUTENTRYYEAR" VARCHAR2(64 BYTE), 
	"INTAKEOUTPUTENTRYTIME24" VARCHAR2(64 BYTE), 
	"INTAKEOUTPUTENTRYTIME" VARCHAR2(64 BYTE), 
	"INTAKEOUTPUTENTRYOFFSET" VARCHAR2(64 BYTE), 
	"CELLPATH" VARCHAR2(500 BYTE), 
	"CELLLABEL" VARCHAR2(256 BYTE), 
	"CELLVALUENUMERIC" VARCHAR2(64 BYTE), 
	"CELLVALUETEXT" VARCHAR2(256 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EICU_V1" ;
--------------------------------------------------------
--  DDL for Table LAB
--------------------------------------------------------

  CREATE TABLE "EICU_V1"."LAB" 
   (	"LABID" NUMBER(*,0), 
	"PATIENTUNITSTAYID" NUMBER(*,0), 
	"LABRESULTYEAR" VARCHAR2(64 BYTE), 
	"LABRESULTTIME24" VARCHAR2(64 BYTE), 
	"LABRESULTTIME" VARCHAR2(64 BYTE), 
	"LABRESULTOFFSET" VARCHAR2(64 BYTE), 
	"LABTYPEID" VARCHAR2(64 BYTE), 
	"LABNAME" VARCHAR2(256 BYTE), 
	"LABRESULT" VARCHAR2(64 BYTE), 
	"LABRESULTTEXT" VARCHAR2(256 BYTE), 
	"LABMEASURENAMESYSTEM" VARCHAR2(256 BYTE), 
	"LABMEASURENAMEINTERFACE" VARCHAR2(256 BYTE), 
	"LABRESULTREVISEDYEAR" VARCHAR2(64 BYTE), 
	"LABRESULTREVISEDTIME24" VARCHAR2(64 BYTE), 
	"LABRESULTREVISEDTIME" VARCHAR2(64 BYTE), 
	"LABRESULTREVISEDOFFSET" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EICU_V1" ;
--------------------------------------------------------
--  DDL for Table MEDICATION
--------------------------------------------------------

  CREATE TABLE "EICU_V1"."MEDICATION" 
   (	"MEDICATIONID" NUMBER(*,0), 
	"PATIENTUNITSTAYID" NUMBER(*,0), 
	"DRUGORDERYEAR" VARCHAR2(64 BYTE), 
	"DRUGORDERTIME24" VARCHAR2(64 BYTE), 
	"DRUGORDERTIME" VARCHAR2(64 BYTE), 
	"DRUGORDEROFFSET" VARCHAR2(64 BYTE), 
	"DRUGSTARTYEAR" VARCHAR2(64 BYTE), 
	"DRUGSTARTTIME24" VARCHAR2(64 BYTE), 
	"DRUGSTARTTIME" VARCHAR2(64 BYTE), 
	"DRUGSTARTOFFSET" VARCHAR2(64 BYTE), 
	"DRUGIVADMIXTURE" VARCHAR2(64 BYTE), 
	"DRUGORDERCANCELLED" VARCHAR2(64 BYTE), 
	"DRUGNAME" VARCHAR2(255 BYTE), 
	"DRUGHICLSEQNO" VARCHAR2(64 BYTE), 
	"DOSAGE" VARCHAR2(400 BYTE), 
	"ROUTEADMIN" VARCHAR2(100 BYTE), 
	"FREQUENCY" VARCHAR2(255 BYTE), 
	"LOADINGDOSE" VARCHAR2(100 BYTE), 
	"PRN" VARCHAR2(64 BYTE), 
	"DRUGSTOPYEAR" VARCHAR2(64 BYTE), 
	"DRUGSTOPTIME24" VARCHAR2(64 BYTE), 
	"DRUGSTOPTIME" VARCHAR2(64 BYTE), 
	"DRUGSTOPOFFSET" VARCHAR2(64 BYTE), 
	"GTC" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EICU_V1" ;
--------------------------------------------------------
--  DDL for Table MICROLAB
--------------------------------------------------------

  CREATE TABLE "EICU_V1"."MICROLAB" 
   (	"MICROLABID" NUMBER(*,0), 
	"PATIENTUNITSTAYID" NUMBER(*,0), 
	"CULTURETAKENYEAR" VARCHAR2(64 BYTE), 
	"CULTURETAKENTIME24" VARCHAR2(64 BYTE), 
	"CULTURETAKENTIME" VARCHAR2(64 BYTE), 
	"CULTURETAKENOFFSET" VARCHAR2(64 BYTE), 
	"CULTURESITE" VARCHAR2(255 BYTE), 
	"ORGANISM" VARCHAR2(255 BYTE), 
	"ANTIBIOTIC" VARCHAR2(255 BYTE), 
	"SENSITIVITYLEVEL" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EICU_V1" ;
--------------------------------------------------------
--  DDL for Table NOTE
--------------------------------------------------------

  CREATE TABLE "EICU_V1"."NOTE" 
   (	"NOTEID" NUMBER(*,0), 
	"PATIENTUNITSTAYID" NUMBER(*,0), 
	"NOTEYEAR" VARCHAR2(64 BYTE), 
	"NOTETIME24" VARCHAR2(64 BYTE), 
	"NOTETIME" VARCHAR2(64 BYTE), 
	"NOTEOFFSET" VARCHAR2(64 BYTE), 
	"NOTEENTEREDYEAR" VARCHAR2(64 BYTE), 
	"NOTEENTEREDTIME24" VARCHAR2(64 BYTE), 
	"NOTEENTEREDTIME" VARCHAR2(64 BYTE), 
	"NOTEENTEREDOFFSET" VARCHAR2(64 BYTE), 
	"NOTETYPE" VARCHAR2(64 BYTE), 
	"NOTEPATH" VARCHAR2(255 BYTE), 
	"NOTEVALUE" VARCHAR2(150 BYTE), 
	"NOTETEXT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EICU_V1" ;
--------------------------------------------------------
--  DDL for Table NURSEASSESSMENT
--------------------------------------------------------

  CREATE TABLE "EICU_V1"."NURSEASSESSMENT" 
   (	"NURSEASSESSID" NUMBER(*,0), 
	"PATIENTUNITSTAYID" NUMBER(*,0), 
	"NURSEASSESSYEAR" VARCHAR2(64 BYTE), 
	"NURSEASSESSTIME24" VARCHAR2(64 BYTE), 
	"NURSEASSESSTIME" VARCHAR2(64 BYTE), 
	"NURSEASSESSOFFSET" VARCHAR2(64 BYTE), 
	"NURSEASSESSENTRYYEAR" VARCHAR2(64 BYTE), 
	"NURSEASSESSENTRYTIME24" VARCHAR2(64 BYTE), 
	"NURSEASSESSENTRYTIME" VARCHAR2(64 BYTE), 
	"NURSEASSESSENTRYOFFSET" VARCHAR2(64 BYTE), 
	"CELLATTRIBUTEPATH" VARCHAR2(255 BYTE), 
	"CELLLABEL" VARCHAR2(255 BYTE), 
	"CELLATTRIBUTE" VARCHAR2(255 BYTE), 
	"CELLATTRIBUTEVALUE" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EICU_V1" ;
--------------------------------------------------------
--  DDL for Table NURSECARE
--------------------------------------------------------

  CREATE TABLE "EICU_V1"."NURSECARE" 
   (	"NURSECAREID" NUMBER(*,0), 
	"PATIENTUNITSTAYID" NUMBER(*,0), 
	"NURSECAREYEAR" VARCHAR2(64 BYTE), 
	"NURSECARETIME24" VARCHAR2(64 BYTE), 
	"NURSECARETIME" VARCHAR2(64 BYTE), 
	"NURSECAREOFFSET" VARCHAR2(64 BYTE), 
	"NURSECAREENTRYYEAR" VARCHAR2(64 BYTE), 
	"NURSECAREENTRYTIME24" VARCHAR2(64 BYTE), 
	"NURSECAREENTRYTIME" VARCHAR2(64 BYTE), 
	"NURSECAREENTRYOFFSET" VARCHAR2(64 BYTE), 
	"CELLATTRIBUTEPATH" VARCHAR2(255 BYTE), 
	"CELLLABEL" VARCHAR2(255 BYTE), 
	"CELLATTRIBUTE" VARCHAR2(255 BYTE), 
	"CELLATTRIBUTEVALUE" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EICU_V1" ;
--------------------------------------------------------
--  DDL for Table NURSECHARTING
--------------------------------------------------------

  CREATE TABLE "EICU_V1"."NURSECHARTING" 
   (	"NURSINGCHARTID" NUMBER(*,0), 
	"PATIENTUNITSTAYID" NUMBER(*,0), 
	"NURSINGCHARTYEAR" VARCHAR2(64 BYTE), 
	"NURSINGCHARTTIME24" VARCHAR2(64 BYTE), 
	"NURSINGCHARTTIME" VARCHAR2(64 BYTE), 
	"NURSINGCHARTOFFSET" VARCHAR2(64 BYTE), 
	"NURSINGCHARTENTRYYEAR" VARCHAR2(64 BYTE), 
	"NURSINGCHARTENTRYTIME24" VARCHAR2(64 BYTE), 
	"NURSINGCHARTENTRYTIME" VARCHAR2(64 BYTE), 
	"NURSINGCHARTENTRYOFFSET" VARCHAR2(64 BYTE), 
	"NURSINGCHARTCELLTYPECAT" VARCHAR2(255 BYTE), 
	"NURSINGCHARTCELLTYPEVALLABEL" VARCHAR2(255 BYTE), 
	"NURSINGCHARTCELLTYPEVALNAME" VARCHAR2(255 BYTE), 
	"NURSINGCHARTVALUE" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EICU_V1" ;
--------------------------------------------------------
--  DDL for Table PASTHISTORY
--------------------------------------------------------

  CREATE TABLE "EICU_V1"."PASTHISTORY" 
   (	"PASTHISTORYID" NUMBER(*,0), 
	"PATIENTUNITSTAYID" NUMBER(*,0), 
	"PASTHISTORYYEAR" VARCHAR2(64 BYTE), 
	"PASTHISTORYTIME24" VARCHAR2(64 BYTE), 
	"PASTHISTORYTIME" VARCHAR2(64 BYTE), 
	"PASTHISTORYOFFSET" VARCHAR2(64 BYTE), 
	"PASTHISTORYENTEREDYEAR" VARCHAR2(64 BYTE), 
	"PASTHISTORYENTEREDTIME24" VARCHAR2(64 BYTE), 
	"PASTHISTORYENTEREDTIME" VARCHAR2(64 BYTE), 
	"PASTHISTORYENTEREDOFFSET" VARCHAR2(64 BYTE), 
	"PASTHISTORYNOTETYPE" VARCHAR2(64 BYTE), 
	"PASTHISTORYPATH" VARCHAR2(255 BYTE), 
	"PASTHISTORYVALUE" VARCHAR2(100 BYTE), 
	"PASTHISTORYVALUETEXT" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EICU_V1" ;
--------------------------------------------------------
--  DDL for Table PATIENT
--------------------------------------------------------

  CREATE TABLE "EICU_V1"."PATIENT" 
   (	"PATIENTUNITSTAYID" NUMBER(*,0), 
	"PATIENTHEALTHSYSTEMSTAYID" NUMBER(*,0), 
	"GENDER" VARCHAR2(64 BYTE), 
	"AGE" VARCHAR2(64 BYTE), 
	"ETHNICITY" VARCHAR2(64 BYTE), 
	"HOSPITALID" VARCHAR2(64 BYTE), 
	"WARDID" VARCHAR2(64 BYTE), 
	"APACHEADMISSIONDX" VARCHAR2(1000 BYTE), 
	"ADMISSIONHEIGHT" VARCHAR2(64 BYTE), 
	"HOSPITALADMITYEAR" VARCHAR2(64 BYTE), 
	"HOSPITALADMITTIME24" VARCHAR2(64 BYTE), 
	"HOSPITALADMITTIME" VARCHAR2(64 BYTE), 
	"HOSPITALADMITOFFSET" VARCHAR2(64 BYTE), 
	"HOSPITALADMITSOURCE" VARCHAR2(64 BYTE), 
	"HOSPITALDISCHARGEYEAR" VARCHAR2(64 BYTE), 
	"HOSPITALDISCHARGETIME24" VARCHAR2(64 BYTE), 
	"HOSPITALDISCHARGETIME" VARCHAR2(64 BYTE), 
	"HOSPITALDISCHARGEOFFSET" VARCHAR2(64 BYTE), 
	"HOSPITALDISCHARGELOCATION" VARCHAR2(64 BYTE), 
	"HOSPITALDISCHARGESTATUS" VARCHAR2(64 BYTE), 
	"UNITTYPE" VARCHAR2(64 BYTE), 
	"UNITADMITYEAR" VARCHAR2(64 BYTE), 
	"UNITADMITTIME24" VARCHAR2(64 BYTE), 
	"UNITADMITTIME" VARCHAR2(64 BYTE), 
	"UNITADMITSOURCE" VARCHAR2(100 BYTE), 
	"UNITVISITNUMBER" VARCHAR2(64 BYTE), 
	"UNITSTAYTYPE" VARCHAR2(64 BYTE), 
	"ADMISSIONWEIGHT" VARCHAR2(64 BYTE), 
	"DISCHARGEWEIGHT" VARCHAR2(64 BYTE), 
	"UNITDISCHARGEYEAR" VARCHAR2(64 BYTE), 
	"UNITDISCHARGETIME24" VARCHAR2(64 BYTE), 
	"UNITDISCHARGETIME" VARCHAR2(64 BYTE), 
	"UNITDISCHARGEOFFSET" VARCHAR2(64 BYTE), 
	"UNITDISCHARGELOCATION" VARCHAR2(100 BYTE), 
	"UNITDISCHARGESTATUS" VARCHAR2(64 BYTE), 
	"AUDITETLRUNID" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EICU_V1" ;
--------------------------------------------------------
--  DDL for Table PHYSICALEXAM
--------------------------------------------------------

  CREATE TABLE "EICU_V1"."PHYSICALEXAM" 
   (	"PHYSICALEXAMID" NUMBER(*,0), 
	"PATIENTUNITSTAYID" NUMBER(*,0), 
	"PHYSICALEXAMYEAR" VARCHAR2(64 BYTE), 
	"PHYSICALEXAMTIME24" VARCHAR2(64 BYTE), 
	"PHYSICALEXAMTIME" VARCHAR2(64 BYTE), 
	"PHYSICALEXAMOFFSET" VARCHAR2(64 BYTE), 
	"PHYSICALEXAMPATH" VARCHAR2(255 BYTE), 
	"PHYSICALEXAMVALUE" VARCHAR2(100 BYTE), 
	"PHYSICALEXAMTEXT" VARCHAR2(500 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EICU_V1" ;
--------------------------------------------------------
--  DDL for Table RESPIRATORYCARE
--------------------------------------------------------

  CREATE TABLE "EICU_V1"."RESPIRATORYCARE" 
   (	"RESPCAREID" NUMBER(*,0), 
	"PATIENTUNITSTAYID" NUMBER(*,0), 
	"RESPCARESTATUSYEAR" VARCHAR2(64 BYTE), 
	"RESPCARESTATUSTIME24" VARCHAR2(64 BYTE), 
	"RESPCARESTATUSTIME" VARCHAR2(64 BYTE), 
	"RESPCARESTATUSOFFSET" VARCHAR2(64 BYTE), 
	"CURRENTHISTORYSEQNUM" VARCHAR2(64 BYTE), 
	"AIRWAYTYPE" VARCHAR2(64 BYTE), 
	"AIRWAYSIZE" VARCHAR2(64 BYTE), 
	"AIRWAYPOSITION" VARCHAR2(64 BYTE), 
	"CUFFPRESSURE" VARCHAR2(64 BYTE), 
	"VENTSTARTYEAR" VARCHAR2(64 BYTE), 
	"VENTSTARTTIME24" VARCHAR2(64 BYTE), 
	"VENTSTARTTIME" VARCHAR2(64 BYTE), 
	"VENTSTARTOFFSET" VARCHAR2(64 BYTE), 
	"VENTENDYEAR" VARCHAR2(64 BYTE), 
	"VENTENDTIME24" VARCHAR2(64 BYTE), 
	"VENTENDTIME" VARCHAR2(64 BYTE), 
	"VENTENDOFFSET" VARCHAR2(64 BYTE), 
	"PRIORVENTSTARTYEAR" VARCHAR2(64 BYTE), 
	"PRIORVENTSTARTTIME24" VARCHAR2(64 BYTE), 
	"PRIORVENTSTARTTIME" VARCHAR2(64 BYTE), 
	"PRIORVENTSTARTOFFSET" VARCHAR2(64 BYTE), 
	"PRIORVENTENDYEAR" VARCHAR2(64 BYTE), 
	"PRIORVENTENDTIME24" VARCHAR2(64 BYTE), 
	"PRIORVENTENDTIME" VARCHAR2(64 BYTE), 
	"PRIORVENTENDOFFSET" VARCHAR2(64 BYTE), 
	"APNEAPARMS" VARCHAR2(64 BYTE), 
	"LOWEXHMVLIMIT" VARCHAR2(64 BYTE), 
	"HIEXHMVLIMIT" VARCHAR2(64 BYTE), 
	"LOWEXHTVLIMIT" VARCHAR2(64 BYTE), 
	"HIPEAKPRESLIMIT" VARCHAR2(64 BYTE), 
	"LOWPEAKPRESLIMIT" VARCHAR2(64 BYTE), 
	"HIRESPRATELIMIT" VARCHAR2(64 BYTE), 
	"LOWRESPRATELIMIT" VARCHAR2(64 BYTE), 
	"SIGHPRESLIMIT" VARCHAR2(64 BYTE), 
	"LOWIRONOXLIMIT" VARCHAR2(64 BYTE), 
	"HIGHIRONOXLIMIT" VARCHAR2(64 BYTE), 
	"MEANAIRWAYPRESLIMIT" VARCHAR2(64 BYTE), 
	"PEEPLIMIT" VARCHAR2(64 BYTE), 
	"CPAPLIMIT" VARCHAR2(64 BYTE), 
	"SETAPNEAINTERVAL" VARCHAR2(80 BYTE), 
	"SETAPNEATV" VARCHAR2(80 BYTE), 
	"SETAPNEAIPPEEPHIGH" VARCHAR2(80 BYTE), 
	"SETAPNEARR" VARCHAR2(80 BYTE), 
	"SETAPNEAPEAKFLOW" VARCHAR2(80 BYTE), 
	"SETAPNEAINSPTIME" VARCHAR2(80 BYTE), 
	"SETAPNEAIE" VARCHAR2(80 BYTE), 
	"SETAPNEAFIO2" VARCHAR2(80 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EICU_V1" ;
--------------------------------------------------------
--  DDL for Table RESPIRATORYCHARTING
--------------------------------------------------------

  CREATE TABLE "EICU_V1"."RESPIRATORYCHARTING" 
   (	"RESPCHARTID" NUMBER(*,0), 
	"PATIENTUNITSTAYID" NUMBER(*,0), 
	"RESPCHARTYEAR" VARCHAR2(64 BYTE), 
	"RESPCHARTTIME24" VARCHAR2(64 BYTE), 
	"RESPCHARTTIME" VARCHAR2(64 BYTE), 
	"RESPCHARTOFFSET" VARCHAR2(64 BYTE), 
	"RESPCHARTENTRYYEAR" VARCHAR2(64 BYTE), 
	"RESPCHARTENTRYTIME24" VARCHAR2(64 BYTE), 
	"RESPCHARTENTRYTIME" VARCHAR2(64 BYTE), 
	"RESPCHARTENTRYOFFSET" VARCHAR2(64 BYTE), 
	"RESPCHARTTYPECAT" VARCHAR2(255 BYTE), 
	"RESPCHARTVALUELABEL" VARCHAR2(255 BYTE), 
	"RESPCHARTVALUE" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EICU_V1" ;
--------------------------------------------------------
--  DDL for Table RSREPORTBUCKET
--------------------------------------------------------

  CREATE TABLE "EICU_V1"."RSREPORTBUCKET" 
   (	"RSREPORTBUCKETID" NUMBER(*,0), 
	"PATIENTUNITSTAYID" NUMBER(*,0), 
	"REPORTCONDITIONCATEGORY" VARCHAR2(64 BYTE), 
	"REPORTCONDITIONDESCRIPTION" VARCHAR2(255 BYTE), 
	"REPORTCONDITIONVALUE" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EICU_V1" ;
--------------------------------------------------------
--  DDL for Table SPERRORLOG
--------------------------------------------------------

  CREATE TABLE "EICU_V1"."SPERRORLOG" 
   (	"USERNAME" VARCHAR2(256 BYTE), 
	"TIMESTAMP" TIMESTAMP (6), 
	"SCRIPT" CLOB, 
	"IDENTIFIER" VARCHAR2(256 BYTE), 
	"MESSAGE" CLOB, 
	"STATEMENT" CLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "EICU_V1" 
 LOB ("SCRIPT") STORE AS BASICFILE (
  TABLESPACE "EICU_V1" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("MESSAGE") STORE AS BASICFILE (
  TABLESPACE "EICU_V1" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("STATEMENT") STORE AS BASICFILE (
  TABLESPACE "EICU_V1" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
--------------------------------------------------------
--  DDL for Table SSADMF
--------------------------------------------------------

  CREATE TABLE "EICU_V1"."SSADMF" 
   (	"PATIENTUNITSTAYID" NUMBER(*,0), 
	"EXPIRATIONYEAR" NUMBER(*,0), 
	"EXPIRATIONOFFSET" VARCHAR2(64 BYTE), 
	"MATCHRULE" VARCHAR2(64 BYTE), 
	"FIXEDDOD" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EICU_V1" ;
--------------------------------------------------------
--  DDL for Table TREATMENT
--------------------------------------------------------

  CREATE TABLE "EICU_V1"."TREATMENT" 
   (	"TREATMENTID" NUMBER(*,0), 
	"PATIENTUNITSTAYID" NUMBER(*,0), 
	"TREATMENTYEAR" VARCHAR2(64 BYTE), 
	"TREATMENTTIME24" VARCHAR2(64 BYTE), 
	"TREATMENTTIME" VARCHAR2(64 BYTE), 
	"TREATMENTOFFSET" VARCHAR2(64 BYTE), 
	"TREATMENTSTRING" VARCHAR2(200 BYTE), 
	"ACTIVEUPONDISCHARGE" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EICU_V1" ;
--------------------------------------------------------
--  DDL for Table VITALAPERIODIC
--------------------------------------------------------

  CREATE TABLE "EICU_V1"."VITALAPERIODIC" 
   (	"VITALAPERIODICID" NUMBER(*,0), 
	"PATIENTUNITSTAYID" NUMBER(*,0), 
	"OBSERVATIONYEAR" VARCHAR2(64 BYTE), 
	"OBSERVATIONTIME24" VARCHAR2(64 BYTE), 
	"OBSERVATIONTIME" VARCHAR2(64 BYTE), 
	"OBSERVATIONOFFSET" VARCHAR2(64 BYTE), 
	"NONINVASIVESYSTOLIC" VARCHAR2(64 BYTE), 
	"NONINVASIVEDIASTOLIC" VARCHAR2(64 BYTE), 
	"NONINVASIVEMEAN" VARCHAR2(64 BYTE), 
	"PAOP" VARCHAR2(64 BYTE), 
	"CARDIACOUTPUT" VARCHAR2(64 BYTE), 
	"CARDIACINPUT" VARCHAR2(64 BYTE), 
	"SVR" VARCHAR2(64 BYTE), 
	"SVRI" VARCHAR2(64 BYTE), 
	"PVR" VARCHAR2(64 BYTE), 
	"PVRI" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EICU_V1" ;
--------------------------------------------------------
--  DDL for Table VITALPERIODIC
--------------------------------------------------------

  CREATE TABLE "EICU_V1"."VITALPERIODIC" 
   (	"VITALPERIODICID" NUMBER(*,0), 
	"PATIENTUNITSTAYID" NUMBER(*,0), 
	"OBSERVATIONYEAR" VARCHAR2(64 BYTE), 
	"OBSERVATIONTIME24" VARCHAR2(64 BYTE), 
	"OBSERVATIONTIME" VARCHAR2(64 BYTE), 
	"OBSERVATIONOFFSET" VARCHAR2(64 BYTE), 
	"TEMPERATURE" VARCHAR2(64 BYTE), 
	"SAO2" VARCHAR2(64 BYTE), 
	"HEARTRATE" VARCHAR2(64 BYTE), 
	"RESPIRATION" VARCHAR2(64 BYTE), 
	"CVP" VARCHAR2(64 BYTE), 
	"ETCO2" VARCHAR2(64 BYTE), 
	"SYSTEMICSYSTOLIC" VARCHAR2(64 BYTE), 
	"SYSTEMICDIASTOLIC" VARCHAR2(64 BYTE), 
	"SYSTEMICMEAN" VARCHAR2(64 BYTE), 
	"PASYSTOLIC" VARCHAR2(64 BYTE), 
	"PADIASTOLIC" VARCHAR2(64 BYTE), 
	"PAMEAN" VARCHAR2(64 BYTE), 
	"ST1" VARCHAR2(64 BYTE), 
	"ST2" VARCHAR2(64 BYTE), 
	"ST3" VARCHAR2(64 BYTE), 
	"ICP" VARCHAR2(64 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "EICU_V1" ;
